//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasT
    {
        public AreasT()
        {
            this.VehicleStatus = new HashSet<VehicleStatus>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Country { get; set; }
        public string AreaCoordinates { get; set; }
    
        public virtual ICollection<VehicleStatus> VehicleStatus { get; set; }
    }
}
