//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlyEntities : DbContext
    {
        public FlyEntities()
            : base("name=FlyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreasT> AreasT { get; set; }
        public DbSet<Riders> Riders { get; set; }
        public DbSet<TripCoordinates> TripCoordinates { get; set; }
        public DbSet<Trips> Trips { get; set; }
        public DbSet<Vehicles> Vehicles { get; set; }
        public DbSet<VehicleSpecs> VehicleSpecs { get; set; }
        public DbSet<VehicleStatus> VehicleStatus { get; set; }
        public DbSet<SecurityRole> SecurityRole { get; set; }
        public DbSet<SecurityUser> SecurityUser { get; set; }
        public DbSet<SecurityUserRole> SecurityUserRole { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
