//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riders
    {
        public Riders()
        {
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Country { get; set; }
        public Nullable<int> City { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool GenderId { get; set; }
    
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
