//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.AreasTMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(AreasT))]
     public partial class AreasT
    {
        public AreasT()
        {
            this.VehicleStatus = new HashSet<VehicleStatus>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public string AreaCoordinates { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<VehicleStatus> VehicleStatus { get; set; }
    }
}
