//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.PromoCodeMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(PromoCode))]
     public partial class PromoCode
    {
        public PromoCode()
        {
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Percentage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
