//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.SecurityUserMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(SecurityUser))]
     public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.SecurityUserRole = new HashSet<SecurityUserRole>();
            this.SubscriptionV = new HashSet<SubscriptionV>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PassCode { get; set; }
        public string IdString { get; set; }
        public string PayMobId { get; set; }
        public Nullable<bool> IsPaied { get; set; }
    
        public virtual ICollection<SecurityUserRole> SecurityUserRole { get; set; }
        public virtual ICollection<SubscriptionV> SubscriptionV { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
