//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.SubscriptionVMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(SubscriptionV))]
     public partial class SubscriptionV
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PhoneNumber { get; set; }
        public string LocationStr { get; set; }
        public string Lng { get; set; }
        public string Lat { get; set; }
        public System.DateTime PickDateTime { get; set; }
        public int DaysCount { get; set; }
        public Nullable<bool> Paied { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string PayMobId { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PromoCodeId { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
