//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.TripsMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(Trips))]
     public partial class Trips
    {
        public Trips()
        {
            this.TripCoordinates = new HashSet<TripCoordinates>();
        }
    
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int RiderId { get; set; }
        public bool IsDone { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> Rate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public bool TempRequest { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> TotalDistance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> WeAcceptOrderId { get; set; }
        public Nullable<int> PromoCodeId { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    
        public virtual PromoCode PromoCode { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual ICollection<TripCoordinates> TripCoordinates { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
