//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.VehicleStatusMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(VehicleStatus))]
     public partial class VehicleStatus
    {
        public int VehicleId { get; set; }
        public string LatV { get; set; }
        public string LongV { get; set; }
        public decimal BatteryStatus { get; set; }
        public bool InRide { get; set; }
        public bool InService { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string VehicleQR { get; set; }
    
        public virtual AreasT AreasT { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
