//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.VehiclesMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(Vehicles))]
     public partial class Vehicles
    {
        public Vehicles()
        {
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SpecsId { get; set; }
        public int ModelId { get; set; }
        public string PlateNo { get; set; }
        public Nullable<int> HolderId { get; set; }
        public bool IsActive { get; set; }
        public string UniqueId { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Trips> Trips { get; set; }
        public virtual VehicleSpecs VehicleSpecs { get; set; }
        public virtual VehicleStatus VehicleStatus { get; set; }
    }
}
