//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fly.DomainModel
{
    using System;
    using System.Collections.Generic;
     using System.Runtime.Serialization;
     using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(Metadata.VehiclesBrandMetadata))]
     [DataContract(IsReference = true)]
     [KnownType(typeof(VehiclesBrand))]
     public partial class VehiclesBrand
    {
        public VehiclesBrand()
        {
            this.VehiclesModel = new HashSet<VehiclesModel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VehiclesModel> VehiclesModel { get; set; }
    }
}
